/**
 * Every user-facing string, from the copy deck in docs/UI-STATES.md. Components import from
 * here and never invent a string, so the same situation reads identically in a notification,
 * a toast and a pane. Add to the deck first, then here.
 */

export const copy = {
  history: {
    searchPlaceholder: 'Search transcripts…',
    empty: 'Nothing dictated yet. Hold right Option and speak.',
    disabled: 'History is off. Turn it on in Settings → Privacy.',
    noMatch: (query: string) => `No transcripts match “${query}”.`,
    loading: 'Loading…',
    notInserted: (reason: string) => `not inserted — ${reason}`,
    items: (n: number) => (n === 1 ? '1 item' : `${n} items`),
    words: (n: number) => (n === 1 ? '1 word' : `${n} words`),
    hints: (n: number) => (n === 1 ? '1 hint' : `${n} hints`),
    deleteAll: 'Delete all…',
    wipeConfirm: (n: number) => `Delete all ${n} transcripts? This can't be undone.`,
    wipeYes: 'Delete',
    wipeNo: 'Cancel',
    copy: 'Copy',
    insert: 'Insert',
    delete: 'Delete',
    more: 'More',
    less: 'Less',
    copied: 'Copied',
    live: {
      arming: 'Opening the microphone…',
      recording: 'Listening…',
      transcribing: 'Transcribing…',
      injecting: 'Placing the text…',
    },
  },
  permissions: {
    missing: {
      inputMonitoring: "Vox can't see the hotkey. Grant Input Monitoring, then quit and reopen Vox.",
      accessibility: "Vox can't place text in other apps. Grant Accessibility, then quit and reopen Vox.",
      microphone: 'No microphone access. Turn it on in System Settings → Privacy → Microphone.',
      inputGroup: "Vox can't read the keyboard. Run `sudo usermod -aG input $USER`, then log out and back in.",
    },
    needsRestart: 'Permission granted. Quit and reopen Vox to use it.',
    openSettings: 'Open System Settings',
    quitAndReopen: 'Quit and reopen',
  },
  settings: {
    panes: {
      dictation: 'Dictation',
      model: 'Model',
      text: 'Text',
      vocabulary: 'Vocabulary',
      privacy: 'Privacy',
      diagnostics: 'Diagnostics',
    },
    dictation: {
      title: 'Hotkey',
      hotkey: 'Hold to dictate',
      hotkeyHint: 'Press the key, speak, let go. Captured by pressing, not by typing a name.',
      pressKeys: 'Press the keys you want to use…',
      altGrWarning: 'On your keyboard layout right Option is AltGr, so holding it changes other keys. Right Control is suggested instead.',
      change: 'Change…',
      mode: 'Mode',
      modeHint: 'Toggle exists because holding a key down is a barrier for some people.',
      modes: { hold: 'Hold', toggle: 'Press to start, press to stop', 'double-tap-hold': 'Double-tap, then hold' },
      cancelKey: 'Cancel',
      cancelHint: 'Press while holding: nothing is transcribed, nothing is kept.',
      minHold: 'Ignore presses shorter than',
      audioTitle: 'Microphone',
      device: 'Input device',
      systemDefault: 'System default',
      noDevices: 'No input devices found. Plug one in, or check System Settings → Sound.',
      level: 'Level',
      levelHint: 'Hold the key and speak to see the level.',
      cap: 'Stop recording after',
      capHint: 'A hold that hits the cap is transcribed as far as it got, and you are told.',
      feedbackTitle: 'While you speak',
      soundCues: 'Play a tone when recording starts and stops',
      soundCuesHint: 'Rising to start, falling to stop, so you know the microphone is open even when the menu bar is on another screen.',
      overlay: 'Show a level meter near the cursor',
      overlayHint: 'A small pill with the level and the elapsed time. It never takes focus and goes away when the text is placed.',
      setupTitle: 'Setup',
      runAgain: 'Run setup again',
      runAgainHint: 'The six first-launch steps, from wherever you left them.',
    },
    model: {
      title: 'Speech recognition',
      note: 'Runs on this Mac. Nothing you say leaves it.',
      builtIn: 'built in',
      languages: 'languages',
      inUse: 'in use',
      use: 'Use',
      download: 'Download',
      downloading: 'Downloading…',
      verifying: 'Verifying…',
      remove: 'Remove',
      none: 'No model installed. Download one, or import a folder.',
      noneHint: 'Dictation is off until one is installed.',
      residency: 'Kept warm while Vox runs',
      residencyHint: 'No memory-versus-speed setting: Vox decides. If that ever feels wrong, that is a bug to report, not a knob to turn.',
      importTitle: 'Import',
      importNote: 'For offline installs: a folder with the model files. Skips the download entirely.',
      importFolder: 'Folder',
      import: 'Import',
      imported: (name: string) => `Imported ${name}.`,
    },
    text: {
      title: 'Placing the text',
      method: 'Method',
      methodHint: 'Auto tries direct insertion, then paste, then typing, and only reports success it can verify.',
      methods: { auto: 'Auto', accessibility: 'Direct insertion', paste: 'Paste', type: 'Type it out' },
      restoreClipboard: 'Restore the clipboard after pasting',
      restoreHint: 'Only once the paste is confirmed. When in doubt the text stays on the clipboard.',
      onFocusChange: 'If you switch apps while speaking',
      onFocusChangeHint: 'Typing into whatever you switched to is worse than not typing.',
      focus: { clipboard: 'Copy instead', 'insert-anyway': 'Insert anyway' },
      shapeTitle: 'Shape',
      trailingSpace: 'Add a space after each dictation',
      capitalizeFirst: 'Capitalise the first word',
      collapseNewlines: 'Collapse line breaks in terminals',
      collapseHint: 'A pasted line break can run a command.',
      dictionaryTitle: 'Custom words',
      dictionaryNote: 'Always replaced, exactly as written. For names the recogniser keeps getting wrong.',
      dictionaryEmpty: "No custom words. Vox learns most of these on its own — add one here if you'd rather not wait.",
      addWord: 'Add',
      heard: 'What it hears',
      meant: 'What you mean',
      add: 'Add',
    },
    vocabulary: {
      title: 'Learning',
      note: "Vox can watch the text field for a short while after it inserts something and notice when you fix a word. After you've corrected a word three times, Vox starts listening for it. It stores the wrong form, the right form, a count, a date and which apps — never the sentences.",
      capture: 'Watch my corrections',
      captureHint: 'Local, kilobytes, deletable any time.',
      apply: 'Apply what it has learned',
      applyHint: 'Off by default. While it is on, the last word of a dictation is dropped now and then. Every learned word is listed below with a delete button.',
      learnedTitle: (n: number) => (n ? `Words Vox has learned (${n})` : 'Words Vox has learned'),
      filter: 'Filter words',
      noMatch: (q: string) => `No learned word matches “${q}”.`,
      empty: 'No words learned yet. Vox picks them up when you correct it.',
      off: "Learning is off. Vox won't watch your corrections. Turn it on to teach it your words.",
      suspended: 'You changed this back twice — Vox has stopped applying it.',
      provenance: (count: number, apps: string[], since: string, was: string[]) =>
        `was ${was.map((w) => `“${w}”`).join(', ')} · ${count} ${count === 1 ? 'correction' : 'corrections'} in ${apps.join(', ')} · since ${since}`,
      waiting: (n: number) => `Waiting: ${n} ${n === 1 ? 'word' : 'words'} seen once or twice`,
      show: 'Show',
      exportLabel: 'Export as a plain list',
      export: 'Export',
      exported: (path: string) => `Exported to ${path}.`,
    },
    privacy: {
      readTitle: 'What Vox may read',
      readField: "Read the field you're dictating into",
      readFieldHint: "Vox looks at the text around your cursor to recognise the names and terms you're likely to say. Read once per dictation, never stored, never leaves this Mac. Off in password fields.",
      historyTitle: 'History',
      historyNote: 'Stored unencrypted in a local database only your account can read. File permissions and full-disk encryption are what protect it.',
      keepHistory: 'Keep a history of what I dictate',
      maxItems: 'Keep at most',
      maxDays: 'Keep for',
      days: 'days',
      zeroUnlimited: '0 means no limit.',
      wipe: 'Delete every transcript',
      wipeButton: 'Delete all…',
      wipeConfirm: "This can't be undone.",
      wiped: (n: number) => `Deleted ${n} ${n === 1 ? 'transcript' : 'transcripts'}.`,
      correctionsTitle: 'Corrections',
      correctionsNote:
        'After Vox places text, it watches that field for 90 seconds and notices when you fix a word. It keeps the wrong form, the right form, a count, the dates and which apps — never the sentence, and never from a password field. Turn it off in Vocabulary.',
      deleteCorrections: 'Delete every correction it has stored',
      deleteCorrectionsButton: 'Delete all…',
      deletedCorrections: (n: number) => `Deleted ${n} ${n === 1 ? 'correction' : 'corrections'}.`,
      networkTitle: 'Network',
      sends: 'Vox makes one request: the update check, which sends nothing but the request itself. There is no analytics endpoint, no crash reporter, no account, and no "anonymous usage statistics" toggle.',
      updateCheck: 'Check for updates',
      updates: { startup: 'When Vox starts', manual: 'Only when I ask', off: 'Never' },
      offlineBlocks: 'Offline lock is on. Turn it off in Privacy to download.',
      offlineLock: 'Offline lock',
      offlineLockHint: 'No socket is opened for any reason, including updates. Survives updates once on.',
      exportTitle: 'Taking your data with you',
      exportNote: 'If this project is ever abandoned, or you find something better, nothing you have accumulated is trapped here.',
      exportEverything: 'History as .md and .json, vocabulary as a plain list',
      exportButton: 'Export everything',
      exporting: 'Exporting…',
      exported: (transcripts: number, words: number, path: string) =>
        `Exported ${transcripts} transcripts and ${words} learned words to ${path}.`,
    },
    diagnostics: {
      trendTitle: 'Corrections per 100 words',
      trendNote: 'The number that says whether Vox is getting better at your words. Computed here, never sent.',
      thin: 'Not enough dictations yet to show a trend.',
      week: 'Week of',
      per100: 'per 100',
      appsTitle: 'Where the text went',
      app: 'App',
      inserted: 'Inserted',
      clipboardOnly: 'Clipboard only',
      timingsTitle: 'Timings and memory',
      timingsNote: 'Medians over recent dictations.',
      capture: 'Capture',
      inference: 'Recognition',
      injection: 'Placing the text',
      memory: 'Memory',
      idle: 'idle',
      peak: 'peak',
      hints: 'Recognition hints',
      hintsHint: 'Names and terms from the field you were dictating into, and your own words. The count per dictation is in the history panel; the terms are never kept.',
      hintsUsed: (withHints: number, dictations: number) => `Sent for ${withHints} of ${dictations} dictations`,
    },
  },
  onboarding: {
    stepOf: (n: number, total: number) => `Step ${n} of ${total}`,
    back: 'Back',
    next: 'Continue',
    done: 'Done',
    runAgain: 'Run setup again',
    steps: {
      intro: {
        title: 'What this does — and whether you need it',
        lines: [
          'Hold a key, speak, let go. Your words appear in the field you were already typing in.',
          'Recognition runs on this Mac. Audio never leaves it.',
          'Everything it keeps is yours to read, export and delete.',
        ],
        honest:
          "Your Mac already has dictation built in, and for short messages it's probably enough. It's in System Settings → Keyboard → Dictation.",
        adds: 'What Vox adds: minutes-long sessions, your own vocabulary, a history of what you said, and the same key on your other machines.',
      },
      setup: {
        title: 'Set up',
        body: 'Three grants and a check. macOS asks for each grant in System Settings and needs Vox reopened afterwards for two of them.',
        microphone: 'Microphone',
        micHint: 'Say something. A meter that moves is the quickest proof the right one is selected.',
        allow: 'Allow',
        denied: 'No microphone access. Turn it on in System Settings → Privacy → Microphone.',
        hearing: 'Hearing you.',
        inputMonitoring: 'Input Monitoring',
        inputMonitoringHint: 'Lets Vox see the key while another app is in front.',
        accessibility: 'Accessibility',
        accessibilityHint: 'Lets Vox place the text in that app.',
        granted: 'Granted',
        needsRestart: 'Granted — reopen Vox to use it',
        open: 'Open System Settings',
        quitAndReopen: 'Quit and reopen',
        engine: 'Speech recognition',
        engineHint: "Apple's engine, on this Mac. Nothing to download.",
        ready: 'Ready',
        unavailable: 'Needs macOS 26 or later',
        checking: 'Checking…',
      },
      tryIt: {
        title: 'Two choices, then try it',
        choices: 'Both off until you say otherwise. Every learned word is listed in Settings → Vocabulary with a delete button; reading the field is once per dictation and never stored.',
        capture: 'Watch my corrections and learn my words',
        captureHint: 'Stores the wrong form, the right form, a count, a date and which apps. Never the sentences.',
        body: 'Hold right Option and say something. Let go, and it appears below.',
        placeholder: 'Your words will appear here.',
        success: "That's it. The key works everywhere from now on.",
        altGr: 'On your keyboard layout right Option is AltGr, so Right Control is suggested instead. Change it in Settings → Dictation.',
      },
    },
  },
  time: {
    justNow: 'just now',
    minutes: (m: number) => `${m} min ago`,
    hours: (h: number) => `${h} h ago`,
    days: (d: number) => `${d} d ago`,
  },
} as const
