/**
 * Every user-facing string, from the copy deck in docs/UI-STATES.md. Components import from
 * here and never invent a string, so the same situation reads identically in a notification,
 * a toast and a pane. Add to the deck first, then here.
 */

export const copy = {
  history: {
    searchPlaceholder: 'Search transcripts…',
    empty: 'Nothing dictated yet. Hold right Option and speak.',
    disabled: 'History is off. Turn it on in Settings → Privacy.',
    noMatch: (query: string) => `No transcripts match “${query}”.`,
    loading: 'Loading…',
    notInserted: (reason: string) => `not inserted — ${reason}`,
    items: (n: number) => (n === 1 ? '1 item' : `${n} items`),
    words: (n: number) => (n === 1 ? '1 word' : `${n} words`),
    deleteAll: 'Delete all…',
    wipeConfirm: (n: number) => `Delete all ${n} transcripts? This can't be undone.`,
    wipeYes: 'Delete',
    wipeNo: 'Cancel',
    copy: 'Copy',
    insert: 'Insert',
    delete: 'Delete',
    more: 'More',
    less: 'Less',
    copied: 'Copied',
    live: {
      arming: 'Opening the microphone…',
      recording: 'Listening…',
      transcribing: 'Transcribing…',
      injecting: 'Placing the text…',
    },
  },
  permissions: {
    missing: {
      inputMonitoring: "Vox can't see the hotkey. Grant Input Monitoring, then quit and reopen Vox.",
      accessibility: "Vox can't place text in other apps. Grant Accessibility, then quit and reopen Vox.",
      microphone: 'No microphone access. Turn it on in System Settings → Privacy → Microphone.',
      inputGroup: "Vox can't read the keyboard. Run `sudo usermod -aG input $USER`, then log out and back in.",
    },
    needsRestart: 'Permission granted. Quit and reopen Vox to use it.',
    openSettings: 'Open System Settings',
    quitAndReopen: 'Quit and reopen',
  },
  settings: {
    panes: {
      dictation: 'Dictation',
      model: 'Model',
      text: 'Text',
      vocabulary: 'Vocabulary',
      privacy: 'Privacy',
      diagnostics: 'Diagnostics',
    },
    dictation: {
      title: 'Hotkey',
      hotkey: 'Hold to dictate',
      hotkeyHint: 'Press the key, speak, let go. Captured by pressing, not by typing a name.',
      pressKeys: 'Press the keys you want to use…',
      altGrWarning: 'On your keyboard layout right Option is AltGr, so holding it changes other keys. Right Control is suggested instead.',
      change: 'Change…',
      mode: 'Mode',
      modeHint: 'Toggle exists because holding a key down is a barrier for some people.',
      modes: { hold: 'Hold', toggle: 'Press to start, press to stop', 'double-tap-hold': 'Double-tap, then hold' },
      cancelKey: 'Cancel',
      cancelHint: 'Press while holding: nothing is transcribed, nothing is kept.',
      minHold: 'Ignore presses shorter than',
      audioTitle: 'Microphone',
      device: 'Input device',
      systemDefault: 'System default',
      noDevices: 'No input devices found. Plug one in, or check System Settings → Sound.',
      level: 'Level',
      levelHint: 'Hold the key and speak to see the level.',
      cap: 'Stop recording after',
      capHint: 'A hold that hits the cap is transcribed as far as it got, and you are told.',
    },
    model: {
      title: 'Speech recognition',
      note: 'Runs on this Mac. Nothing you say leaves it.',
      builtIn: 'built in',
      languages: 'languages',
      inUse: 'in use',
      use: 'Use',
      download: 'Download',
      downloading: 'Downloading…',
      verifying: 'Verifying…',
      remove: 'Remove',
      none: 'No model installed. Download one, or import a folder.',
      noneHint: 'Dictation is off until one is installed.',
      residency: 'Kept warm while Vox runs',
      residencyHint: 'No memory-versus-speed setting: Vox decides. If that ever feels wrong, that is a bug to report, not a knob to turn.',
      importTitle: 'Import',
      importNote: 'For offline installs: a folder with the model files. Skips the download entirely.',
      importFolder: 'Folder',
      import: 'Import',
      imported: (name: string) => `Imported ${name}.`,
    },
    text: {
      title: 'Placing the text',
      method: 'Method',
      methodHint: 'Auto tries direct insertion, then paste, then typing, and only reports success it can verify.',
      methods: { auto: 'Auto', accessibility: 'Direct insertion', paste: 'Paste', type: 'Type it out' },
      restoreClipboard: 'Restore the clipboard after pasting',
      restoreHint: 'Only once the paste is confirmed. When in doubt the text stays on the clipboard.',
      onFocusChange: 'If you switch apps while speaking',
      onFocusChangeHint: 'Typing into whatever you switched to is worse than not typing.',
      focus: { clipboard: 'Copy instead', 'insert-anyway': 'Insert anyway' },
      shapeTitle: 'Shape',
      trailingSpace: 'Add a space after each dictation',
      capitalizeFirst: 'Capitalise the first word',
      collapseNewlines: 'Collapse line breaks in terminals',
      collapseHint: 'A pasted line break can run a command.',
      dictionaryTitle: 'Custom words',
      dictionaryNote: 'Always replaced, exactly as written. For names the recogniser keeps getting wrong.',
      dictionaryEmpty: "No custom words. Vox learns most of these on its own — add one here if you'd rather not wait.",
      addWord: 'Add',
      heard: 'What it hears',
      meant: 'What you mean',
      add: 'Add',
    },
    vocabulary: {
      title: 'Learning',
      note: 'Vox can watch the text field for a short while after it inserts something and notice when you fix a word. After the same fix three times, it starts making it for you. It stores the wrong form, the right form, a count, a date and which apps — never the sentences.',
      capture: 'Watch my corrections',
      captureHint: 'Local, kilobytes, deletable any time.',
      apply: 'Apply what it has learned',
      applyHint: 'Off by default. Every applied term is listed below with a delete button.',
      learnedTitle: 'Words Vox has learned',
      empty: 'No words learned yet. Vox picks them up when you correct it.',
      off: "Learning is off. Vox won't watch your corrections. Turn it on to teach it your words.",
      suspended: 'You changed this back twice — Vox has stopped applying it.',
      provenance: (count: number, apps: string[], since: string, was: string) =>
        `was “${was}” · ${count} ${count === 1 ? 'correction' : 'corrections'} in ${apps.join(', ')} · since ${since}`,
      waiting: (n: number) => `Waiting: ${n} ${n === 1 ? 'word' : 'words'} seen once or twice`,
      show: 'Show',
      exportLabel: 'Export as a plain list',
      export: 'Export',
      exported: (path: string) => `Exported to ${path}.`,
    },
    privacy: {
      readTitle: 'What Vox may read',
      readField: "Read the field you're dictating into",
      readFieldHint: "Vox looks at the text around your cursor to recognise the names and terms you're likely to say. Read once per dictation, never stored, never leaves this Mac. Off in password fields.",
      historyTitle: 'History',
      historyNote: 'Stored unencrypted in a local database only your account can read. File permissions and full-disk encryption are what protect it.',
      keepHistory: 'Keep a history of what I dictate',
      maxItems: 'Keep at most',
      maxDays: 'Keep for',
      days: 'days',
      zeroUnlimited: '0 means no limit.',
      wipe: 'Delete every transcript',
      wipeButton: 'Delete all…',
      wipeConfirm: "This can't be undone.",
      wiped: (n: number) => `Deleted ${n} ${n === 1 ? 'transcript' : 'transcripts'}.`,
      networkTitle: 'Network',
      sends: 'Vox makes one request: the update check, which sends nothing but the request itself. There is no analytics endpoint, no crash reporter, no account, and no "anonymous usage statistics" toggle.',
      updateCheck: 'Check for updates',
      updates: { startup: 'When Vox starts', manual: 'Only when I ask', off: 'Never' },
      offlineBlocks: 'Offline lock is on. Turn it off in Privacy to download.',
      offlineLock: 'Offline lock',
      offlineLockHint: 'No socket is opened for any reason, including updates. Survives updates once on.',
      exportTitle: 'Taking your data with you',
      exportNote: 'If this project is ever abandoned, or you find something better, nothing you have accumulated is trapped here.',
      exportEverything: 'History as .md and .json, vocabulary as a plain list',
      exportButton: 'Export everything',
      exporting: 'Exporting…',
      exported: (transcripts: number, words: number, path: string) =>
        `Exported ${transcripts} transcripts and ${words} learned words to ${path}.`,
    },
    diagnostics: {
      trendTitle: 'Corrections per 100 words',
      trendNote: 'The number that says whether Vox is getting better at your words. Computed here, never sent.',
      thin: 'Not enough dictations yet to show a trend.',
      week: 'Week of',
      per100: 'per 100',
      appsTitle: 'Where the text went',
      app: 'App',
      inserted: 'Inserted',
      clipboardOnly: 'Clipboard only',
      timingsTitle: 'Timings and memory',
      timingsNote: 'Medians over recent dictations.',
      capture: 'Capture',
      inference: 'Recognition',
      injection: 'Placing the text',
      memory: 'Memory',
      idle: 'idle',
      peak: 'peak',
    },
  },
  time: {
    justNow: 'just now',
    minutes: (m: number) => `${m} min ago`,
    hours: (h: number) => `${h} h ago`,
    days: (d: number) => `${d} d ago`,
  },
} as const
